zeebe:
  client:
    cloud:
      region: bru-2
      clusterId: 9f7e711d-8ac9-4ffd-ab16-1cbfe8e3a50f
      clientId: rD50-FtqNWhA4uGV0o4EW5-o7ES0J~.B
      clientSecret: ufOrTDgehSx.OJUoxF1fkHC9IU..BB6bJalbxl-abemXq.wDUpNv.3XB7.A9uMK4

someSecretPassword: jkl&jo8987(+998?